### ISSUE TITLE
【feature request】Support functional pages created by other plugin such as 'Calendar' page created by the full calendar plugin 

### ISSUE THREAD

**Issue by Ravenclawer** [hdykokd/obsidian-vertical-tabs-view#15]
The pages that are created by other plugins like the full calendar are not included in the vertical tabs view plugin for now

**Comment by hdykokd** [comment]
Thank you for your request. I'll give it a try.

**Comment by hdykokd** [comment]
I've released it as [1.0.4](https://github.com/hdykokd/obsidian-vertical-tabs-view/releases/tag/1.0.4). Please update to this version. @Ravenclawer

**Comment by Ravenclawer** [comment]
Thank you so much. It works like a charm
