### ISSUE TITLE
【bug report】when there are like 20 tabs and scroll down to bottom to close a tab, the scroll position will automatically scroll to top

### ISSUE THREAD

**Issue by Ravenclawer** [hdykokd/obsidian-vertical-tabs-view#37]

**Comment by Ravenclawer** [comment]
I am still on 2.0.4. I will update the plugin and check again

**Comment by Ravenclawer** [comment]
The problem seems to reverse in 2.0.17, when you at top and close a tab. it will scroll down to the bottom

**Comment by hdykokd** [comment]
Thank you for the report.
I cannot reproduce the issue in my environment (macOS 13.5.1, Obsidian v1.4.5).
Could you provide more details about your environment, and it would be easier to understand the situation if you could attach a screen capture.

**Comment by hdykokd** [comment]
It reproduced on iOS

**Comment by Ravenclawer** [comment]
I am on obsidian 1.4.12, windows 11
