### ISSUE TITLE
[FR] Hide the directory 

### ISSUE THREAD

**Issue by wwjCMP** [hdykokd/obsidian-vertical-tabs-view#38]
Sometimes we don't care about the file's location.

**Comment by hdykokd** [comment]
I've released it as [2.2.0](https://github.com/hdykokd/obsidian-vertical-tabs-view/releases/tag/2.2.0).
Now, you can toggle this feature in the settings.

![CleanShot 2023-10-28 at 19 02 40@2x](https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/19975408/e5e8e0a8-6849-40d5-9cd2-b0f9a0434140)
