### ISSUE TITLE
Feature request: Select multiple tabs

### ISSUE THREAD

**Issue by nickchomey** [hdykokd/obsidian-vertical-tabs-view#43]
It would be great if we could press shift or tab to select multiple tabs, so that we can close them or perform other right click actions

**Comment by elegios** [comment]
[Sidebery](https://addons.mozilla.org/en-US/firefox/addon/sidebery/) (vertical tabs in firefox) has an interesting take on this, you right-click drag over a number of tabs, then when you release the button it opens a menu that will act on those tabs.

**Comment by hdykokd** [comment]
> [Sidebery](https://addons.mozilla.org/en-US/firefox/addon/sidebery/) (vertical tabs in firefox) has an interesting take on this, you right-click drag over a number of tabs, then when you release the button it opens a menu that will act on those tabs.

I gave it a try. This is an interesting feature. It might be convenient once I get used to it.
