### ISSUE TITLE
Feature request: Right click menu

### ISSUE THREAD

**Issue by nickchomey** [hdykokd/obsidian-vertical-tabs-view#44]
It would be great if the standard obsidian right click menu worked on the vertical tabs

**Comment by hdykokd** [comment]
[Menu - Developer Documentation](https://docs.obsidian.md/Reference/TypeScript+API/Menu)

I overlooked that Obsidian provides a context menu feature.
We may be able to accomplish this by using this. I'll investigate.

**Comment by hdykokd** [comment]
I understand that we can use the UI provided by Obsidian, but it seems that we should emulate the native menu items.

**Comment by hdykokd** [comment]
- Open in new tab
- Open to the right
- Open in new window
---
- Rename
- Make a copy
- Move file to ...
- Bookmark ...
- Merge entire file with...
---
- Open in default app (macOS specific?)
- Reveal in Finder (macOS specific?)
--- 
- Copy Obsidian URL
