### ISSUE TITLE
obsidian light mode difficult see vertical tabs view

### ISSUE THREAD

**Issue by Leiyi548** [hdykokd/obsidian-vertical-tabs-view#58]
![image](https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/76139422/66f22be3-9ae5-4a88-b6fe-e91997109b24)

**Comment by Leiyi548** [comment]
@hdykokd 
![image](https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/76139422/7b105cae-6876-4985-a4eb-9cee1e0494f2)
not correct

**Comment by hdykokd** [comment]
Ah, sorry. Not released yet.

**Comment by hdykokd** [comment]
I apologize for the inconvenience. I have released a fixed version as 2.4.1.
