### ISSUE TITLE
feature request : support icons from iconize

### ISSUE THREAD

**Issue by Rhydderch** [hdykokd/obsidian-vertical-tabs-view#68]
Hi,

Thank you for this plugin.

Would it be possible for the plugin to support icons defined using the frontmatter with the iconize plugin? [https://github.com/FlorianWoelki/obsidian-iconize](https://github.com/FlorianWoelki/obsidian-iconize) 

This feature would make the tab even more visual. For example, I have custom icons for daily notes
<img width="551" alt="image" src="https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/3197629/29b71863-0ffe-4402-9d5e-fb0f5a56aafd">
<img width="389" alt="image" src="https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/3197629/ea34d579-b300-4b33-99e9-c52b8760e72f">

**Comment by hdykokd** [comment]
Hi! I wasn't aware of this plugin. That's an interesting idea. I'll look into it when I have some free time.

**Comment by hdykokd** [comment]
After #78 is released, if the "Toggle icon in tabs" option in iconize's General settings is enabled, it will also be reflected in the tab icon in Vertical Tabs View.

![CleanShot 2024-04-18 at 00 31 54@2x](https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/19975408/df6c1517-32ee-4d66-9cf9-c0d4136d87c0)
