### ISSUE TITLE
Typo in context menu

### ISSUE THREAD

**Issue by nickchomey** [hdykokd/obsidian-vertical-tabs-view#69]
It says "Trach" rather than "Trash"
https://github.com/hdykokd/obsidian-vertical-tabs-view/blob/main/src/components/Tabs.svelte#L336
https://github.com/hdykokd/obsidian-vertical-tabs-view/blob/main/src/components/Tabs.svelte#L345

Though, what do Trash Local and Trash System even mean? How do they differ from each other, and from Delete File?

**Comment by hdykokd** [comment]
Obsidian's built-in Delete File feature allows you to specify where deleted files are stored, based on your settings. You can choose to have them go either to a Obsidian's trash folder (.trash) or to the system's Trash folder.
In other words, "Trash Local" or "Trash System" are referring to those two options. As you might have guessed, it was a bit of a hassle to identify the specific API that provides the same functionality as the Delete File feature, so for now, both options have been implemented.
