### ISSUE TITLE
Pins unnecessarily increase row height

### ISSUE THREAD

**Issue by nickchomey** [hdykokd/obsidian-vertical-tabs-view#70]
When some notes are pinned, the row height is excessively large
![image](https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/88559987/b18a2e30-39fc-4342-ae54-a7cf2d93407d)

If I unpin them, they shrink. 
![image](https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/88559987/6d7b485a-6323-4a7e-bf5c-63cf54dbca19)

It would be nice if the pin was the same height as the text.

**Comment by hdykokd** [comment]
I'm sorry for the inconvenience. I also apologize for the delayed response - I didn't notice this feedback. @naomu worked on this. Please look forward to the release.
