### ISSUE TITLE
Error loading plugin on mobile

### ISSUE THREAD

**Issue by MrBertie** [hdykokd/obsidian-vertical-tabs-view#81]
The plugin does not function on mobile for me, when I check in vConsole I see the following error message: 

```
Uncaught (in promise)  {"name": "TypeError", "message": "Cannot use 'in' operator to search for 'customizeTabIcon' in null", "stack": "TypeError: Cannot use 'in' operator to search for 'customizeTabIcon' in null\n    at fa.loadSettings (plugin:vertical-tabs-view:6:72429)\n    at async fa.onload (plugin:vertical-tabs-view:6:71820)"}
```

**Comment by hdykokd** [comment]
I'm sorry. I would appreciate it if you could update to [v2.5.2](https://github.com/hdykokd/obsidian-vertical-tabs-view/releases/tag/2.5.2) and check if the problem is resolved.

**Comment by hdykokd** [comment]
@MrBertie I'm sorry. I would appreciate it if you could update to [v2.5.2](https://github.com/hdykokd/obsidian-vertical-tabs-view/releases/tag/2.5.2) and check if the problem is resolved.

**Comment by MrBertie** [comment]
> @MrBertie I'm sorry. I would appreciate it if you could update to [v2.5.2](https://github.com/hdykokd/obsidian-vertical-tabs-view/releases/tag/2.5.2) and check if the problem is resolved.

Thank you kindly, I tried the new version, and yes, it now loads without an error. The Settings page works correctly, however I do not see the plugin in the sidebar. Is there something I still need to do to activate it?

**Comment by hdykokd** [comment]
> The Settings page works correctly, however I do not see the plugin in the sidebar. Is there something I still need to do to activate it?

Please try searching for `Vertical Tabs View: Show vertical tabs view` in Command palette and running it.

![CleanShot 2024-04-18 at 15 32 28@2x](https://github.com/hdykokd/obsidian-vertical-tabs-view/assets/19975408/b5391a92-db4c-4fd2-9bd0-b3aabbafabc7)

**Comment by MrBertie** [comment]
Perfect!

**Comment by hdykokd** [comment]
I'm glad it worked! Thank you for using this plugin.
