### ISSUE TITLE
The order of vertical tabs doesn’t sync with the order of actual tabs

### ISSUE THREAD

**Issue by gchegr** [hdykokd/obsidian-vertical-tabs-view#88]
I’ve installed the plugin and discovered the order it displays the rows is different from the one I have my tabs in.
I made some experiments and figured these just don’t sync. If I move my original tabs, the vertical order stays the same and vise versa.
I later discovered the About page says this clearly, but I don’t think this is OK :)
So I am making a request (even perhaps it’s not possible to achieve this) to make them sync.

**Comment by hdykokd** [comment]
Thank you for your request. I also think it would be ideal if synchronization were possible, but I was unable to implement this because Obsidian does not provide an API that enables this.
